create table if not exists public.enrollment_submissions_trabajo (
  id bigint generated by default as identity primary key,
  first_names text not null check (char_length(btrim(first_names)) between 1 and 120),
  last_names text not null check (char_length(btrim(last_names)) between 1 and 120),
  dni varchar(8) not null check (dni ~ '^[0-9]{7,8}$'),
  gender text not null check (gender in ('Masculino', 'Femenino', 'No binario', 'Otro')),
  email text not null check (char_length(btrim(email)) between 1 and 160),
  phone varchar(10) not null check (phone ~ '^[0-9]{1,10}$'),
  workplace text not null check (char_length(btrim(workplace)) between 1 and 180),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint enrollment_submissions_trabajo_dni_key unique (dni)
);

create index if not exists enrollment_submissions_trabajo_created_at_idx
  on public.enrollment_submissions_trabajo (created_at desc);

alter table public.enrollment_submissions_trabajo enable row level security;
